# Nomad agent config — production server+client node
#
# Deploy: sudo cp nomad/config/server.hcl /etc/nomad.d/server.hcl
# Or use the automated setup script (recommended):
#   sudo bash scripts/setup_node.sh --advertise-ip <NODE_IP> [--vault-node]
#
# Manual steps if copying directly:
#   1. Replace NODE_ADVERTISE_IP with the actual public IP of this node.
#   2. On the Vault/deploy node only: keep  meta { vault_server = "true" }
#   3. On other (client-only) nodes: remove the meta block entirely.
#
# vault.hcl and volumes.hcl are separate files — Nomad loads all *.hcl
# files in /etc/nomad.d/ as config fragments. Do NOT merge them here.

datacenter = "dc1"
data_dir   = "/opt/nomad"
bind_addr  = "0.0.0.0"
log_level  = "INFO"

server {
  enabled          = true
  bootstrap_expect = 1   # set to the number of server nodes in the cluster
}

client {
  enabled = true

  meta {
    # Remove this block on non-server nodes.
    # Vault job is pinned here — deploy script uses VAULT_ADDR=127.0.0.1
    vault_server = "true"
  }

  options = {
    "driver.raw_exec.enable" = "1"
  }
}

# Each node must advertise its own reachable IP so cross-host RPC works.
# Replace NODE_ADVERTISE_IP with this node's public/private IP.
advertise {
  http = "NODE_ADVERTISE_IP"
  rpc  = "NODE_ADVERTISE_IP"
  serf = "NODE_ADVERTISE_IP"
}

# Mutual TLS — required when Nomad runs with TLS enabled.
# Cert files are generated by `nomad tls cert create` and placed in /etc/nomad.d/.
tls {
  http = true
  rpc  = true

  ca_file   = "/etc/nomad.d/nomad-agent-ca.pem"
  cert_file = "/etc/nomad.d/global-server-nomad.pem"
  key_file  = "/etc/nomad.d/global-server-nomad-key.pem"

  verify_server_hostname = true
}

# Allow privileged Docker containers (needed by some infra jobs).
plugin "docker" {
  config {
    allow_privileged = true
  }
}

# ACL — enable token-based access control.
acl {
  enabled = true
}

# Consul integration
consul {
  address = "127.0.0.1:8500"
}
